@startuml
left to right direction
skinparam packageStyle rect
actor User
actor Admin
rectangle "用户管理" as UM {
  User --> (注册登录)
  User --> (用户信息管理)
  User --> (查询图书)
}
rectangle "借阅管理" as BM {
  User --> (借阅图书)
  User --> (归还图书)
  Admin --> (借阅信息管理)
}
rectangle "收藏管理" as CM {
  User --> (收藏图书)
  User --> (查看收藏图书)
}
rectangle "图书信息管理" as BIM {
  User --> (查看所有图书信息)
  User --> (查询图书)
}
rectangle "管理员" as AdminPanel {
  Admin --> UM
  Admin --> BM
  Admin --> CM
  Admin --> BIM
  rectangle "管理员功能" as AF {
    Admin --> (修改、禁用、删除用户)
    Admin --> (删除借阅信息)
    Admin --> (查看所有用户的收藏)
    Admin --> (修改图书信息)
    Admin --> (删除图书信息)
    Admin --> (生成统计图表)
    Admin --> (查看统计图表)
    }
}
UM -down-> BM
BM -down-> CM
CM -down-> BIM
BIM -down-> AF
@enduml
